# Generated by Django 3.1.6 on 2021-02-21 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('banner', models.ImageField(null=True, upload_to='campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_published', models.DateField(auto_now=True)),
                ('welcome_message', models.TextField(blank=True)),
                ('question', models.CharField(blank=True, max_length=255)),
                ('response1', models.CharField(blank=True, max_length=255)),
                ('response2', models.CharField(blank=True, max_length=255)),
                ('response3', models.CharField(blank=True, max_length=255)),
                ('devotional', models.TextField(blank=True)),
                ('prayer', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('youtube_id', models.CharField(max_length=255)),
                ('streamevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.streamevent')),
            ],
        ),
    ]
